Create nina.md
id-mozilla/hacktoberfest-2022 pull request #10
Opened 2022-10-21 09:33 UTC by NinaWulansari

2022-10-22 09:48 UTC, greenbrown requested changes

2022-10-22 09:48 UTC, greenbrown commented on common-voice/nina/nina.md
> +| | ninawulan | 19/10/2022 | 23.01 | 80 Klip |
Jangan lupa upload screenshotnya - dasbor Common Voice kalau kelewatan mesti ulang lagi ya nanti :D

2022-10-26 06:31 UTC, NinaWulansari commented
#Hacktoberfest [1] Nama: Nina Wulansari (ninawulan) [2] Tanggal/Waktu Kontribusi: 25/10/2022 - 16.10 [3] Jumlah klip: 121

2022-10-26 09:09 UTC, greenbrown approved these changes
![congrat2](https://user-images.githubusercontent.com/49750588/197985041-7bb7d8c8-1e2f-4ded-aa7a-8d1037e8e46a.gif)

2022-10-26 09:10 UTC, merged